name: DotnetSixProjectBuilder
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true  
        
    # CustomerSet.Find.InOut.csproj
    
    - name: Restore NewSearilizationTester.csproj
      run: dotnet restore ./src/*/NewSearilizationTester.csproj

    - name: Build NewSearilizationTester.csproj
      run: dotnet build ./src/*/NewSearilizationTester.csproj --no-restore  -c Release

    - name: Run NewSearilizationTester.csproj
      run: dotnet run ./src/*/NewSearilizationTester.csproj --no-restore  -c Release
